import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SideHeader } from "@/components/side-header";
import { CustomTriggerHeader } from "@/components/custom-trigger-header";
import { Toaster } from "sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StaffLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider defaultOpen={false}>
          <SideHeader />
          <div className="md:hidden">
            <CustomTriggerHeader />
          </div>

          <main className="w-full">
            <div className="mx-5 mt-13 mb-5">{children}</div>
          </main>
        </SidebarProvider>
        <Toaster position="top-center" richColors />
        <SpeedInsights />
      </body>
    </html>
  );
}
